spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://root:example@mongodb:27017/ordersdb?authSource=admin&retryWrites=true&retryReads=true
      auto-index-creation: true
  redis:
    host: redis
    port: 6379
    timeout: 60000
    connect-timeout: 60000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
      shutdown-timeout: 100ms
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    mongo:
      enabled: true
    redis:
      enabled: true

server:
  port: 8080

logging:
  level:
    io.lettuce.core: DEBUG
    org.springframework.data.redis: DEBUG